--What it tells you:-
--Success/Fail status: A permanent record of every run.
--Row Counts: Proof that 50 rows were moved.
SELECT * FROM PIPELINE_LOGS ORDER BY RUN_TIMESTAMP DESC;

-- 1. THE HEARTBEAT (Proves NRT Status)
SELECT 
    MAX(INGESTION_TIME) as LAST_REFRESH,
    DATEDIFF('minute', MAX(INGESTION_TIME), CURRENT_TIMESTAMP()) as MINUTES_AGO
FROM COIN_DATA;

-- 2. THE MOMENTUM DASHBOARD (The "Star" Feature)
-- This calculates growth compared to your very first run!
WITH stats AS (
    SELECT 
        SYMBOL,
        CURRENT_PRICE,
        FIRST_VALUE(CURRENT_PRICE) OVER (PARTITION BY SYMBOL ORDER BY INGESTION_TIME ASC) as START_PRICE,
        LAG(CURRENT_PRICE) OVER (PARTITION BY SYMBOL ORDER BY INGESTION_TIME ASC) as PREV_PRICE,
        INGESTION_TIME
    FROM COIN_DATA
)
SELECT 
    SYMBOL,
    CURRENT_PRICE as NOW,
    ROUND(((CURRENT_PRICE - START_PRICE) / NULLIF(START_PRICE, 0)) * 100, 2) as TOTAL_GROWTH_PCT,
    ROUND(((CURRENT_PRICE - PREV_PRICE) / NULLIF(PREV_PRICE, 0)) * 100, 2) as HOURLY_MOMENTUM_PCT
FROM stats
QUALIFY ROW_NUMBER() OVER (PARTITION BY SYMBOL ORDER BY INGESTION_TIME DESC) = 1
ORDER BY TOTAL_GROWTH_PCT DESC;

-- 3. IDEMPOTENCY AUDIT (Proves No Duplicates)
SELECT ID, INGESTION_TIME, COUNT(*) 
FROM COIN_DATA 
GROUP BY 1, 2 
HAVING COUNT(*) > 1;